### ISSUE TITLE
Be sure the collection is tested against 2.11 and contains ignore-2.12.txt if applicable

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ibm.qradar#38]
##### SUMMARY
Be sure the collection is tested against 2.11 and contains ignore-2.12.txt if applicable

https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100

If everything is OK, feel free to close the issue

**Comment by craig-br** [comment]
@anshulbehl 
I've tested the IBM QRadar collection with AAP 2.0 and get a version compatibility warning AAP 2. This is using an execution environment based on `ansible-automation-platform-20-early-access/ee-minimal-rhel8`.

#### command
```bash
[student1@ansible-1 ~]$ ansible-navigator run enrich_log_sources.yml --mode stdout
[WARNING]: Collection ibm.qradar does not support Ansible version 2.11.2
```

#### ansible version
```yaml
SECURITY_EE:LATEST (PRIMARY) (INFORMATION ABOUT ANSIBLE AND ANSIBLE COLLECTIONS)                                                                                                        
 0│---
 1│ansible:
 2│  collections:
 3│    details:
 4│      ansible.netcommon: 2.3.0
 5│      ansible.security: 1.0.0
 6│      ansible.utils: 2.3.1
 7│      awx.awx: 19.2.2
 8│      check_point.mgmt: 2.0.0
 9│      cisco.asa: 2.0.2
10│      community.general: 3.5.0
11│      ibm.qradar: 1.0.3
12│      splunk.es: 1.0.2
13│      trendmicro.deepsec: 1.1.0
14│  version:
15│    details: core 2.11.2
```
### Temp workaround

Messages can be suppressed by adding `collections_on_ansible_version_mismatch = ignore` entry to the `ansible.cfg` file
